### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by leorsousa05** [leorsousa05/FoxPouch#4]
I need CI/CD for the project.

**Comment by jbonadiman** [comment]
Hi! 👋
So, I tried to compile/run the project locally so I could start devising a CI/CD pipeline, but I couldn´t. These are the steps I took:

```
$ git clone git@github.com:leorsousa05/FoxPouch.git
$ cd FoxPouch

$ ls

Permissions Size User Date Modified Name
.rw-r--r--   436 user 15 Mar 10:44   .eslintrc.cjs
drwxr-xr-x     - user 15 Mar 10:44   .git/
.rw-r--r--   253 user 15 Mar 10:44   .gitignore
.rw-r--r--  2.0k user 15 Mar 10:44   index.html
.rw-r--r--  1.1k user 15 Mar 10:44   LICENSE
.rw-r--r--  114k user 15 Mar 10:44   package-lock.json
.rw-r--r--  1.0k user 15 Mar 10:44   package.json
drwxr-xr-x     - user 15 Mar 10:44   public/
.rw-r--r--     1 user 15 Mar 10:44   README.md
drwxr-xr-x     - user 15 Mar 10:44   src/
drwxr-xr-x     - user 15 Mar 10:44   src-tauri/
.rw-r--r--   605 user 15 Mar 10:44   tsconfig.json
.rw-r--r--   213 user 15 Mar 10:44   tsconfig.node.json
.rw-r--r--   189 user 15 Mar 10:44   vite.config.ts

$ pnpm install
$ cd src-tauri
$ ls

Permissions Size User Date Modified Name
.rw-r--r--    73 user 15 Mar 10:44   .gitignore
.rw-r--r--    37 user 15 Mar 10:44   build.rs
.rw-r--r--  123k user 15 Mar 10:44   Cargo.lock
.rw-r--r--   542 user 15 Mar 10:44   Cargo.toml
drwxr-xr-x     - user 15 Mar 10:44   icons/
.rw-r--r--    38 user 15 Mar 10:44   settings.cfg
drwxr-xr-x     - user 15 Mar 10:44   src/
.rw-r--r--  2.0k user 15 Mar 10:44   tauri.conf.json

$ cargo build
$ ls

Permissions Size User Date Modified Name
.rw-r--r--    73 user 15 Mar 10:44   .gitignore
.rw-r--r--    37 user 15 Mar 10:44   build.rs
.rw-r--r--  123k user 15 Mar 10:47   Cargo.lock
.rw-r--r--   542 user 15 Mar 10:44   Cargo.toml
drwxr-xr-x     - user 15 Mar 10:44   icons/
.rw-r--r--    38 user 15 Mar 10:44   settings.cfg
drwxr-xr-x     - user 15 Mar 10:44   src/
drwxr-xr-x     - user 15 Mar 10:49   target/                    <---- new folder
.rw-r--r--  2.0k user 15 Mar 10:44   tauri.conf.json

$ tree -L 2 target

target
├── CACHEDIR.TAG
└── debug
    ├── app
    ├── app.d
    ├── build
    ├── deps
    ├── examples
    └── incremental

6 directories, 3 files

$ target/debug/app
```
And it opens this window:
![image](https://github.com/leorsousa05/FoxPouch/assets/18357636/e943b4ff-dbfb-4037-81bd-5577405ca8b4)

Could you tell me what I did wrong and give me updated steps to run the project?

**Comment by leorsousa05** [comment]
> Hi! 👋
> So, I tried to compile/run the project locally so I could start devising a CI/CD pipeline, but I couldn´t. These are the steps I took:
> 
> ```
> $ git clone git@github.com:leorsousa05/FoxPouch.git
> $ cd FoxPouch
> 
> $ ls
> 
> Permissions Size User Date Modified Name
> .rw-r--r--   436 user 15 Mar 10:44   .eslintrc.cjs
> drwxr-xr-x     - user 15 Mar 10:44   .git/
> .rw-r--r--   253 user 15 Mar 10:44   .gitignore
> .rw-r--r--  2.0k user 15 Mar 10:44   index.html
> .rw-r--r--  1.1k user 15 Mar 10:44   LICENSE
> .rw-r--r--  114k user 15 Mar 10:44   package-lock.json
> .rw-r--r--  1.0k user 15 Mar 10:44   package.json
> drwxr-xr-x     - user 15 Mar 10:44   public/
> .rw-r--r--     1 user 15 Mar 10:44   README.md
> drwxr-xr-x     - user 15 Mar 10:44   src/
> drwxr-xr-x     - user 15 Mar 10:44   src-tauri/
> .rw-r--r--   605 user 15 Mar 10:44   tsconfig.json
> .rw-r--r--   213 user 15 Mar 10:44   tsconfig.node.json
> .rw-r--r--   189 user 15 Mar 10:44   vite.config.ts
> 
> $ pnpm install
> $ cd src-tauri
> $ ls
> 
> Permissions Size User Date Modified Name
> .rw-r--r--    73 user 15 Mar 10:44   .gitignore
> .rw-r--r--    37 user 15 Mar 10:44   build.rs
> .rw-r--r--  123k user 15 Mar 10:44   Cargo.lock
> .rw-r--r--   542 user 15 Mar 10:44   Cargo.toml
> drwxr-xr-x     - user 15 Mar 10:44   icons/
> .rw-r--r--    38 user 15 Mar 10:44   settings.cfg
> drwxr-xr-x     - user 15 Mar 10:44   src/
> .rw-r--r--  2.0k user 15 Mar 10:44   tauri.conf.json
> 
> $ cargo build
> $ ls
> 
> Permissions Size User Date Modified Name
> .rw-r--r--    73 user 15 Mar 10:44   .gitignore
> .rw-r--r--    37 user 15 Mar 10:44   build.rs
> .rw-r--r--  123k user 15 Mar 10:47   Cargo.lock
> .rw-r--r--   542 user 15 Mar 10:44   Cargo.toml
> drwxr-xr-x     - user 15 Mar 10:44   icons/
> .rw-r--r--    38 user 15 Mar 10:44   settings.cfg
> drwxr-xr-x     - user 15 Mar 10:44   src/
> drwxr-xr-x     - user 15 Mar 10:49   target/                    <---- new folder
> .rw-r--r--  2.0k user 15 Mar 10:44   tauri.conf.json
> 
> $ tree -L 2 target
> 
> target
> ├── CACHEDIR.TAG
> └── debug
>     ├── app
>     ├── app.d
>     ├── build
>     ├── deps
>     ├── examples
>     └── incremental
> 
> 6 directories, 3 files
> 
> $ target/debug/app
> ```
> And it opens this window:
> ![image](https://github.com/leorsousa05/FoxPouch/assets/18357636/e943b4ff-dbfb-4037-81bd-5577405ca8b4)
> 
> Could you tell me what I did wrong and give me updated steps to run the project?
> 

For running the project, you just need to go back to the root of the project and run "npm run tauri-dev", the target folder it's just for running the production executable!

**Comment by jbonadiman** [comment]
> For running the project, you just need to go back to the root of the project and run "npm run tauri-dev", the target folder it's just for running the production executable!

It ran flawlessly now, thanks!
And how do you get from that to the .exe you distribute in itch.io?

**Comment by leorsousa05** [comment]
> It ran flawlessly now, thanks! And how do you get from that to the .exe you distribute in itch.io?

So you have to go to: src-tauri\target\release\bundle\msi

There you'll find a Windows Installer, i install it and get the executable from where i installed the program and zip it to Itch.io. If you want, it's better to just use the Windows Installer instead of making these whole process 😂.
